### ISSUE TITLE
Recommended changes resulting from automated audit

### ISSUE THREAD

**Issue by Jericho** [cake-contrib/Cake.Unity#10]
We performed an automated audit of your Cake addin and found that it does not follow all the best practices.

We encourage you to make the following modifications:

- [x] You are currently referencing Cake.Core 0.17.0. Please upgrade to 0.28.0
- [x] Your addin should target netstandard2.0. Please note that there is no need to multi-target, netstandard2.0 is sufficient.
- [x] The nuget package for your addin should use the cake-contrib icon. Specifically, your addin's `.csproj` should have a line like this: `<PackageIconUrl>https://cdn.rawgit.com/cake-contrib/graphics/a5cf0f881c390650144b2243ae551d5b9f836196/png/cake-contrib-medium.png</PackageIconUrl>`.

Apologies if this is already being worked on, or if there are existing open issues, this issue was created based on what is currently published for this package on NuGet.org and in the project on github.

**Comment by kolesnick** [comment]
Fixed in https://github.com/cake-contrib/Cake.Unity/commit/6dcf98677852a75728752b326e65e00dbac28b67, https://github.com/cake-contrib/Cake.Unity/commit/696114916306df48bdd0a08545f3f362727e34c2 and https://github.com/cake-contrib/Cake.Unity/commit/e854e0369cd15d869a34ec25df6fd0e3f358965a
