### ISSUE TITLE
Fix automated build script

### ISSUE THREAD

**Issue by kolesnick** [cake-contrib/Cake.Unity#13]
Automated build script is out of date with tooling being used and does not pass.
Update it and fix other issues.

**Comment by gep13** [comment]
@kolesnick let me know if you have any questions in this area.

**Comment by kolesnick** [comment]
@gep13 this is backward-tracking issue which I noted for milestone. Thank you!

**Comment by kolesnick** [comment]
Fixed in https://github.com/cake-contrib/Cake.Unity/commit/d31fcc00ebd6474f62705893bd4b7eeb5ec5238d
