### ISSUE TITLE
Cake.Core 1.1.0

### ISSUE THREAD

**Issue by kolesnick** [cake-contrib/Cake.Unity#58]

**Comment by kolesnick** [comment]
closed via https://github.com/cake-contrib/Cake.Unity/commit/701a7054d7c4d44ac354d46ef87843ac12c25c3e

**Comment by augustoproiete** [comment]
Hey @kolesnick I noticed that you updated the [Cake.Core](https://github.com/cake-contrib/Cake.Unity/commit/701a7054d7c4d44ac354d46ef87843ac12c25c3e#diff-20157f7eb25e200f464aab8ca52894d0a2a512da60e4d78b106a5166008c4ee6R11) to `1.1.0` and just wanted to send you a note that there are no breaking changes to the API between Cake `1.0.0` and Cake `1.1.0`, and your addin doesn't seem to rely on anything new added to `1.1.0` so you should be able to safely target Cake `1.0.0` for broader reach.

i.e. If you target Cake `1.0.0`, your addin can be used with Cake `1.0.0` and higher.

More info: https://cakebuild.net/docs/extending/addins/best-practices#references

**Comment by kolesnick** [comment]
@augustoproiete Thank you! Switched to 1.0.0.
