### ISSUE TITLE
Convert this repo to use Cake.Recipe

### ISSUE THREAD

**Issue by gep13** [cake-contrib/Cake.Unity#6]
@patriksvensson I am pretty much at the point where my not so secret project, Cake.Recipe, is ready to be rolled out.

Would you be interested in me adding it to this repository?

The benefits would be...

- a single place to control all the builds in the cake-contrib organisation
- access to notifications on twitter and gitter when new releases are available

Things that Cake.Recipe already does:

- Version with GitVersion
- Build
- Compile
- Run Unit Tests
- Submit results to coveralls.io
- NuGet Package everything
- Upload all artifacts to AppVeyor
- Runs DupFinder
- Runs InspectCode
- Handles publishing to both MyGet and NuGet (for interim releases)
- Runs GitLink, meaning that addin code is debuggable doing debug session in visual studio when debugging build.cake
- Documentation Website generation using Wyam

Probably other stuff that I have forgotten.

The main thing being, if we add something to Cake.Recipe, then all projects that are already using Cake.Recipe should be able to immediately take advantage of it.

Thoughts?  If you were interested, would you be happy to have me make the changes directly to repo, or would you prefer it as a PR?

**Comment by patriksvensson** [comment]
Closed via #7.
