### ISSUE TITLE
Cake.Unity Version 0.9 not downloadable?

### ISSUE THREAD

**Issue by codewing** [cake-contrib/Cake.Unity#68]
You've released 0.9.0 to nuget but (at least my cake tool) doesn't seem to get it and the cake website also states that the latest release is 0.8.1.

Do you have to do something to update it to the latest version [here](https://www.cakebuild.net/extensions/cake-unity/) or do I have to do something other than changing the dependency in the cake files?

**Comment by kolesnick** [comment]
@codewing Sorry, I missed the issue. Is everything OK now?

**Comment by codewing** [comment]
No worries, the issue was just that the pipeline that automatically updates the website broke - I've asked there as well and it got fixed immediately. Thanks for asking!
