### ISSUE TITLE
Push a version to NuGet.org

### ISSUE THREAD

**Issue by gep13** [cake-contrib/Cake.Unity#8]
@patriksvensson doesn't look like this has ever made it to NuGet.org.

Is it in a position where a version could be pushed?  Seems a shame to not have it out there.

**Comment by patriksvensson** [comment]
@gep13 Sure. Let me give it a try.

**Comment by rdavisunr** [comment]
@patriksvensson - I would also love to see this on NuGet.org...

**Comment by kolesnick** [comment]
Done! https://www.nuget.org/packages/Cake.Unity
